### PR TITLE
style: Style match to mockup

### PR DESCRIPTION
**Pull request by mathiuskitchens**
[optional body]

[optional footer(s)]

# Description

<<_Please include a summary of the change._>>

## Type of change

- [ ] - fix: - patches a bug in the codebase
- [ ] - feat: - introduces a new feature
- [ ] - build: - relates to build tooling / project scaffolding
- [ ] - chore: - non-code related changes, like adding packages / libraries
- [ ] - docs: - changes related to documentation
- [x] - style: - updates styling of page

## Related Issue

Does this change have a related issue in the project?

- [ ] - Yes - Closes <<_Add issue number prefixed with `#` sign_>>
- [x] - No

### CODE REVIEW

**Comment by wijohnst** [comment]
When I ran the application locally I got a build error about the `src` attribute on the `img.poke-image` tag. It says you can't have a `src` attribute with an empty string for a value. I was able to get it to build by removing `src` from that tag.

**Review by wijohnst — CHANGES_REQUESTED** [review]
Looks good. See my comment in the `Conversation` tab. Please address empty `src` tag and I'll be happy to approve.

**Comment by mathiuskitchens** [comment]
> Looks good. See my comment in the `Conversation` tab. Please address empty `src` tag and I'll be happy to approve.

I removed the src tag. Let me know if that fixes the build error you got

**Review by wijohnst — APPROVED** [review]
Ship 🚢

**Pull request merged**
